#!/usr/bin/env python3
#coding=utf8

import hprof

def _shorten(s, maxlength):
	l = len(s)
	if l > maxlength:
		return s[:min(l, maxlength-3)] + '...'
	return s

def dump(hfile):
	for r in hfile.records():
		data = _shorten(str(r), 100)
		print('%10x: %s %-10s %s' % (r.hprof_addr, r.timestamp.strftime('%H:%M:%S.%f'), type(r).__name__, data))

if __name__ == '__main__':
	import sys
	for filename in sys.argv[1:]:
		with hprof.open(filename) as hf:
			stars = max(0, (96 - len(filename)))
			lstars = stars // 2
			rstars = stars - lstars
			print(lstars * '*' + '* ' + filename + ' *' + rstars * '*')
			dump(hf)
