#!/usr/bin/env python3
#coding=utf8

import hprof

def _shorten(s, maxlength):
	l = len(s)
	if l > maxlength:
		return s[:min(l, maxlength-3)] + '...'
	return s

def dump(hfile):
	for di, d in enumerate(hfile.dumps()):
		for hi, h in enumerate(d.heaps()):
			print('DUMP %d, HEAP %d: %s' % (di, hi, h))
			for obj in heap.objects():
				print(obj)
		data = _shorten(str(r), 100)
		print('%10x: %s %3d/%-10s %s' % (r.addr, r.timestamp.strftime('%H:%M:%S.%f'), r.tag, type(r).__name__, data))

if __name__ == '__main__':
	import sys
	for filename in sys.argv[1:]:
		stars = max(0, (96 - len(filename)))
		lstars = stars // 2
		rstars = stars - lstars
		print(lstars * '*' + '* ' + filename + ' *' + rstars * '*')
		with hprof.open(filename) as hf:
			dump(hf)
