#!/bin/bash

echo
echo '------------------------------ DOC TESTS -----------------------------'
if [ $# -eq 0 ]; then
	python3 -m unittest discover -p doctests.py
fi

echo
echo '------------------------------ UNITTESTS -----------------------------'
mkdir -p coverage
rm coverage/*,cover
python3-coverage erase
python3-coverage run -m unittest discover "$@"

echo
echo "Coverage report (see 'coverage' dir for annotated sources):"
python3-coverage report --omit='tests/*'
python3-coverage annotate -d coverage --omit='tests/*'
